### ISSUE TITLE
Twitch-Specific IRC Capabilities

### ISSUE THREAD

**Issue by JoshuaSkelly** [JoshuaSkelly/twitch-observer#13]
# Overview
Add support for the Twitch-specific IRC capabilities.

# Children
- [x] [Twitch IRC Capability: Membership #14](https://github.com/JoshuaSkelly/twitch-observer/issues/14)
- [x] [Twitch IRC Capability: Tags #15](https://github.com/JoshuaSkelly/twitch-observer/issues/15)
- [x] [Twitch IRC Capability: Commands #16](https://github.com/JoshuaSkelly/twitch-observer/issues/16)

**Comment by JoshuaSkelly** [comment]
I've committed changes to address #14 and @PythooonUser is working on #16

**Comment by PythooonUser** [comment]
I've commited changes regarding #16

**Comment by JoshuaSkelly** [comment]
All the child user stories are complete! 🎉 

Should we call this feature done?

**Comment by PythooonUser** [comment]
Yes, we should call it done. 🎈
